### ISSUE TITLE
请问没开track_running_stats的InstanceNorm会不会导致因果性的问题？

### ISSUE THREAD

**Issue by SherryYu33** [cszheng-ioa/Sixty-years-of-frequency-domain-monaural-speech-enhancement#2]
您好

我发现代码中CTSNet、G2Net、TaylorSENet中都使用了非因果的、没开track_running_stats的InstanceNorm，是否应该打开track_running_stats？或者说应该使用CumulativeLayerNorm？

谢谢！

**Comment by cszheng-ioa** [comment]
您好
由于CTSNet、G2Net、TaylorSENet是实验室比较早期使用的模型，确实存在InstanceNorm实际是非因果的问题。但是由于训练数据的动态范围比较小，所以性能影响并不大。我们后期的模型确实改为使用CumulativeLayerNorm了。
